name: Build AAB File And Automation EAS Submit

on:
  push:
    branches:
      - prod # Specify the branches that will trigger the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Java 17 environment
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Use the Eclipse Temurin distribution
          java-version: "17"

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the node version compatible with your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      #Keystore setup v1
      - name: Decode and save the .jks file
        run: |
          echo "$MY_JKS_SECRET" | base64 --decode > $HOME/my-release-key.jks

      #Keystore setup v2
      - name: Set up environment variables for Gradle
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=$HOME/my-release-key.jks" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_STORE_PASSWORD=$MYAPP_UPLOAD_STORE_PASSWORD" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_ALIAS=$MYAPP_UPLOAD_KEY_ALIAS" >> $GITHUB_ENV
          echo "MYAPP_UPLOAD_KEY_PASSWORD=$MYAPP_UPLOAD_KEY_PASSWORD" >> $GITHUB_ENV

      # Make gradlew executable
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      # Build AAB file
      - name: Build AAB file
        run: |
          cd android
          ./gradlew bundleRelease

      # Setup Expo and EAS
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create Google Services JSON key
        run: |
          mkdir -p secrets
          echo "${{ secrets.ENCODED_GOOGLE_SERVICE_ACCOUNT_KEY }}" | base64 -d > secrets/service-account-key.json
        shell: bash

      - name: EAS submit
        run: eas submit -p android --path ./android/app/build/outputs/bundle/release/app-release.aab
